config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :products do
    resources :questions, only: [:new, :create,:edit,:update]
  end

  get 'pages/:id', to: 'pages#sales', as: 'sales'
  get 'home_products', to: 'pages#home_products', as: 'home_products'
  get 'load_more', to: 'pages#load_more'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    mount_uploader :product_photo, PhotoUploader
    mount_uploader :category_photo, PhotoUploader

  belongs_to :owner, class_name: 'User', foreign_key: 'owner_id'
  belongs_to :buyer, class_name: 'User', foreign_key: 'buyer_id', optional: true
  has_many :questions, dependent: :destroy
  has_many :askers, through: :questions
  validates :product_type, :category, :description, :price, :memory, :color, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :asker, class_name: 'User', foreign_key: 'user_id'
  belongs_to :product
  validates :asker, :question_description, presence: true
  validates :answer_description, presence: true, allow_nil: true
end

app/models/user.rb
class User < ApplicationRecord
    mount_uploader :user_photo, PhotoUploader

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :products, foreign_key: 'owner_id'
  has_many :questions
  validates :first_name, :last_name, presence: true, allow_nil: true

  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:home, :show, :home_products]
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :user_photo, :user_photo_cache])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :user_photo, :user_photo_cache])
  end

  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
   flash[:alert] = "You are not authorized to perform this action."
   redirect_to(root_path)
 end

 private

 def skip_pundit?
  devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @products = Product.limit(6)
  end

  def sales
    @product = Product.find(params[:id])
  end

  def home_products
    @products = Product.where(sold: false).limit(6)
    if params[:product_type]
      @products = @products.where(product_type: params[:product_type])
    end
  end

  def load_more
    @products = Product.limit(9)
    respond_to do |format|
      format.js { render :load_more }
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]
  skip_after_action :verify_policy_scoped, only: [ :index ]


  def index
    @products = policy_scope(Product).where(owner: current_user)
  end

  def show
    @questions = Question.where(product: @product)
    authorize @questions
    @question = Question.new
    authorize @question
  end

  def new
    @product = Product.new
    authorize @product
  end

  def create
    @product = Product.new(product_params)
    authorize @product
    @product.owner = current_user
    set_standard_photo(@product)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def update
    if @product.update(product_params)
      redirect_to product_path(@product)
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:price, :model, :memory, :color, :status,
      :photo, :description, :category, :product_type,
      :version, :owner_id, :buyer_id, :product_photo, :product_photo_cache)
  end


  def set_product
    @product = Product.find(params[:id])
    authorize @product
  end

  def set_standard_photo(product_object)

    stock_photo = {
      'iPhone'=> 'iphone_geral.jpeg',
      'iPhone 3G' => 'iphone3g.jpeg',
      'iPhone 3GS' => 'iphone3gs.jpeg',
      'iPhone 4' => 'iphone4.png',
      'iPhone 4S' => 'iphone4s.jpeg',
      'iPhone 5' => 'iphone5.jpg',
      'iPhone 5C' => 'iphone5c.png',
      'iPhone 5S' => 'iphone5s.jpeg',
      'iPhone 6 / 6 Plus' => 'iphone6.jpeg',
      'iPhone 6S / 6S Plus' => 'iphone6s.jpeg',
      'iPhone SE' => 'iphonese.jpeg',
      'iPhone 7 / 7 Plus' => 'iphone7.jpeg',
      'iPhone 8 / 8 Plus' => 'iphone8.jpeg',
      'iPhone X' => 'iphonex.jpeg'
    }
    product_object.photo = stock_photo[product_object.category]
  end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_product, only: [:create, :update, :new, :edit]
  before_action :set_user, only: [:create, :new,:edit, :update]
  before_action :set_question, only: [:edit ,:update]

  def new
    @question = Question.new
    authorize @question
  end

  def create
    @question = Question.new(check_questions_params)
    authorize @question
    @question.asker = @user
    @question.product = @product
    if @question.save
      respond_to  do |format|
        format.html {redirect_to product_path(@product)}
        format.js
      end
    else
      respond_to do |format|
        format.html { render 'shared/form_questions'}
        format.js
      end
    end
  end

  def edit
  end

  def update

    if @question.update(check_questions_params)
      redirect_to product_path(@product)
    else
      render :new
    end
  end

  private

  def check_questions_params
    params.require(:question).permit(:question_description, :answer_description)
  end

  def set_user
    @user = current_user
  end

  def set_question
    @question = Question.find(params[:id])
    authorize @question
  end

  def set_product
    @product = Product.find(params[:product_id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper


  def unanswered_questions
    @products = []
    products = current_user.products
    products.each do |product|
      product.questions.each do |question|
        if question.answer_description == nil
          @products << product
        end
      end
    end
    @products.uniq
  end


  def question_count
    @counter = 0
    products = current_user.products
    products.each do |product|
      product.questions.each do |question|
        if question.answer_description == nil
          @counter += 1
        end
      end
    end
    @counter
  end


  def categories
    @categories = []
    products = Product.all
    products.each do |product|
      @categories << product.product_type
    end
    @categories.uniq
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Feira da Maçã | Seminovos da Apple</title>
  <!-- Google result description-->
  <meta name="description" content="Compre produtos Apple seminovos 100% originais">
  <meta property="og:title" content="Feira da Maçã é a loja online de produtos Apple seminovos">
  <meta property="og:image" content="http://res.cloudinary.com/dsxbknylk/image/upload/v1522967521/foto-card.png">
  <meta property="og:description" content="Aqui você encontra aquele produto Apple que tanto deseja por um preço ótimo.">
  <meta property="og:site_name" content="feira da maça"/>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117045853-1"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-117045853-1');
  </script>

</head>
<header>
  <%= render 'shared/navbar' %>
</header>
<body>
    <%= render 'shared/flashes' %>
      <%= yield %>
      <%= javascript_include_tag 'application' %>
      <%= javascript_pack_tag 'application' %>
  <footer>
    <%= render 'shared/footer' %>
  </footer>
</body>
</html>

app/views/pages/home.html.erb
  <div class="container-banner"><div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('http://res.cloudinary.com/dsxbknylk/image/upload/v1522964912/background.jpg');">
    <div class="banner-content">
      <h1>Feira da Maçã</h1>
      <p>Compra e Venda de produtos da Apple</p>
      <%= link_to "Ver todos produtos", home_products_path, class: "btn btn-primary btn-lg" %>
    </div>

  </div>



<div class="container">

  <h3 id="destaques">Últimos destaques</h1>
  <div class="row" id="products-container">

    <% @products.each do |product| %>

      <% path = cl_image_path "#{product.photo}"  %>
      <% if product[:product_photo].nil? %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= path %>');">
          <div class="card-category">

          <%= link_to product.category, product_path(product), class: "text-card-category" %>

          </div>
          <div class="card-description">
            <h2>$<%= product.price %>.00</h2>
            <p>Cor:<%= product.color.capitalize%></p>


            <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% else %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path product.product_photo, height: 300, width: 400, crop: :fill %>');">
          <div class="card-category"><%= product.category %></div>
          <div class="card-description">
            <h2>$<%= product.price %></h2>
            <p>Cor:<%= product.color%></p>

            <%= link_to "<i class='fa fa-eye'></i> Ver produto".html_safe, product_path(product), class: "btn btn-primary" %>
            <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
  </div>

</div>

app/views/pages/home_products.html.erb
<div class="container-fluid">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9 col-sm-push-3">
      <button type="button" class="pull-left btn btn-default visible-xs" data-toggle="offcanvas" aria-expanded="false" aria-controls="navbar">
        <i class="fa fa-navicon"></i>
      </button>
      <!-- <div class="jumbotron">
        <h1>Produtos</h1>
        <p>Aqui você encontra o produto ideal para você</p>
      </div> -->
      <h1>Produtos</h1>
      <div class="row" id="products-container">
        <% @products.each do |product| %>
        <% path = cl_image_path "#{product.photo}"  %>
        <% if product[:product_photo].nil? %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= path %>');">
            <div class="card-category">
              <%= link_to product.category, product_path(product), class: "text-card-category" %>
            </div>
            <div class="card-description">
              <h2>$<%= product.price %>.00</h2>
              <p>Cor:<%= product.color.capitalize%></p>


              <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
            </div>
          </div>
        </div>
        <% else %>
        <div class="col-xs-12 col-sm-4">
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path product.product_photo, height: 300, width: 400, crop: :fill %>');">
            <div class="card-category"><%= product.category %></div>
            <div class="card-description">
              <h2>$<%= product.price %></h2>
              <p>Cor:<%= product.color%></p>

              <%= link_to "<i class='fa fa-eye'></i> Ver produto".html_safe, product_path(product), class: "btn btn-primary" %>
              <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
            </div>
          </div>
        </div>
        <% end %>
        <% end %>

      </div><!--/row-->
        <div class="more-prod">
    <%= link_to "Mais produtos", load_more_path, class: "btn btn-default", remote: true %>
   </div>
    </div><!--/.col-xs-12.col-sm-9-->

    <div class="col-xs-6 col-sm-3 col-sm-pull-9 sidebar-offcanvas" id="sidebar">
      <div class="list-group">
        <a href="#" class="list-group-item active">Todos</a>
        <% categories.each do |category| %>
          <%= link_to category, home_products_path(product_type: category), class: "list-group-item" %>
        <% end %>
      </div>
    </div><!--/.sidebar-offcanvas-->
  </div><!--/row-->

  <hr>

</div><!--/.container-->

app/views/pages/load_more.js.erb
products_container = document.getElementById('products-container')

query_return = `

       <% @products.each do |product| %>
      <% path = cl_image_path "#{product.photo}"  %>
      <% if product[:product_photo].nil? %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= path %>');">
          <div class="card-category">

          <%= link_to product.category, product_path(product), class: "text-card-category" %>

          </div>
          <div class="card-description">
            <h2>$<%= product.price %>.00</h2>
            <p>Cor:<%= product.color.capitalize%></p>


            <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% else %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path product.product_photo, height: 300, width: 400, crop: :fill %>');">
          <div class="card-category"><%= product.category %></div>
          <div class="card-description">
            <h2>$<%= product.price %></h2>
            <p>Cor:<%= product.color%></p>

            <%= link_to "<i class='fa fa-eye'></i> Ver produto".html_safe, product_path(product), class: "btn btn-primary" %>
            <%= link_to "<i class='fa fa-shopping-cart'></i> Comprar".html_safe, sales_path(product), class: "btn btn-danger" %>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>

`

 products_container.insertAdjacentHTML('beforeend', query_return)

app/views/products/edit.html.erb
<%= render "form", type: "Edit product" %>

app/views/products/index.html.erb
<div class="container">

  <h1>Meus produtos</h1>
  <% if @products.count != 0 %>

  <div class="row">
    <% @products.each do |product| %>
    <% if  product[:product_photo].nil? %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('../assets/<%=product.photo%>');">
        <div class="card-category"><%= product.category %></div>
        <div class="card-description">
          <h2>$<%= product.price %></h2>
          <p>color:<%= product.color%></p>
          <%= link_to "<i class='fa fa-eye'></i> View".html_safe, product_path(product), class: "btn btn-primary" %>
          <%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_product_path(product), class: "btn btn-default", class: 'btn btn-warning btn-md' %>
          <%= link_to '<i class="fa fa-trash"></i> Trash'.html_safe, product_path(product), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-md' %>
        </div>
      </div>
    </div>
    <% else %>
    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= cl_image_path product.product_photo, height: 300, width: 400, crop: :fill %>');">
        <div class="card-category"><%= product.category %></div>
        <div class="card-description">
          <h2>$<%= product.price %></h2>
          <p>color:<%= product.color%></p>
          <%= link_to "<i class='fa fa-eye'></i> View".html_safe, product_path(product), class: "btn btn-primary" %>
          <%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_product_path(product), class: "btn btn-default", class: 'btn btn-warning btn-md' %>
          <%= link_to '<i class="fa fa-trash"></i> Trash'.html_safe, product_path(product), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-md' %>
        </div>
      </div>
    </div>
    <% end %>
    <% end %>
  </div>
  <%#= link_to '<i class="fa fa-home"></i> Home'.html_safe, root_path, class: 'btn btn-primary btn-lg'  %>

  <% else %>

  <p>Não existem produtos cadastrados</p>

  <% end %>
</div>

app/views/products/show.html.erb
<div class="container">
  <% col = ' col-sm-12' %>
  <% col1 = ' col-sm-12 col-md-3' %>
  <% col2 = ' col-sm-12 col-md-8' %>
  <% col3 = ' col-sm-12 col-md-1' %>


<% if user_signed_in? %>
  <%  if current_user[:user_photo].nil? %>
    <% user_image_path = 'https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/user.png' %>
  <% else %>
    <% user_image_path = cl_image_path "#{current_user.user_photo}" %>
  <% end %>
  <% else %>
    <% user_image_path = 'https://www.iconexperience.com/_img/o_collection_png/green_dark_grey/512x512/plain/user.png' %>
<% end %>



<div class="wrapper">


  <div class="container">
    <div class="row">
      <h1><%= @product.description%></h1>
      <% path = cl_image_path "#{@product.photo}"  %>



      <div class="banner-small" style="background-image:  url('<%= path %>');">
          <div class="banner-content">
          </div>
      </div>


      <% if !@product[:product_photo].nil? %>
        <div class="product-photo <%=col %>">
          <%= cl_image_tag @product.product_photo, height: 300, width: 400, crop: :fill %>
        </div>
      <% end %>

      <table class="table table-striped <%=col%>">
        <tr>
          <th>price</th>
          <th>model_code</th>
          <th>memory</th>
          <th>color</th>
          <th>status</th>
          <th>description</th>
          <th>category</th>
          <th>product_type</th>
          <th>version</th>
        </tr>
        <tr>
          <td>
            <%= @product.price  %>
          </td>
          <td>
            <%= @product.model_code  %>
          </td>
          <td>
            <%= @product.memory  %>
          </td>
          <td>
            <%= @product.color  %>
          </td>
          <td>
            <%= @product.description  %>
          </td>
          <td>
            <%= @product.category  %>
          </td>
          <td>
            <%= @product.product_type  %>
          </td>
          <td>
            <%= @product.version  %>
          </td>
        </tr>
      </table>
      <div class="button-container<%=col%>">
        <%= link_to "<i class='fa fa-shopping-cart'></i> Buy".html_safe, sales_path(@product), class: "btn btn-danger btn-lg" %>
        <% if current_user == @product.owner %>
        <%= link_to '<i class="fa fa-edit"></i> Edit'.html_safe, edit_product_path, class: "btn btn-default", class: 'btn btn-warning btn-md' %>
        <%= link_to '<i class="fa fa-trash"></i> Trash'.html_safe, product_path(@product), method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger btn-md' %>

        <% end %>
      </div>
      <%if User.all.include?(current_user) %>
        <h4>Contact the seller</h4>
        <div class="question-box <%=col%>">
          <%= render 'shared/form_questions', product: @product, question: @question %>
        </div>
      <% end %>
      <% if @questions.length > 0 %>
          <h2>This is are the questions for product id: <%= @product.id  %> </h2>
          <% end %>
      <div id="questions">

        <% if @questions.length > 0 %>


          <div class="questions-container"'>
            <% @questions.reverse.each do |question|  %>
              <div class="message question row" >
                <img class="avatar-large" src="<%=user_image_path %>">
                <div class="message-name <%=col1%>">
                  <h3><%= question.asker.first_name %></h3>
                  <p><%= question.created_at %></p>
                </div>
                <div class="message-body <%=col2%>">
                  <p>
                    <strong>
                      <%= question.question_description.split[0]%>
                      <%= question.question_description.split[1]%>
                    </strong>
                  </p>
                  <p>
                    <%= question.question_description %>
                  </p>
                </div>
                <div class="message-status <%=col3%>">
                  <p class="status declined">Question</p>
                  <p class="price"></p>
                </div>
              </div>
              <% if current_user == question.product.owner && question.answer_description.nil? %>
                <div class="answer-box row">
                  <%= render partial: 'shared/form_answers', locals: { question: question} %>
                </div>
              <% end %>
              <% if !question.answer_description.nil? %>
                <div class="message answer row">
                  <img class="avatar-large" src="<%=user_image_path %>">
                  <div class="message-name <%=col1%>">
                    <h3><%= question.product.owner.first_name %></h3>
                    <p><%= question.updated_at %></p>
                  </div>
                  <div class="message-body <%=col2%>">
                    <p>
                      <strong>
                        <%= question.answer_description.split[0]%>
                        <%= question.answer_description.split[1]%>
                      </strong>
                    </p>
                    <p>
                      <%= question.answer_description %>
                    </p>
                  </div>
                  <div class="message-status <%=col3%>">
                    <p class="status accepted">Answer</p>
                    <p class="price"></p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
  <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add Product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Products", products_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% if question_count != 0 %>
        <div class="dropdown">
          <%= link_to "Questions (#{question_count})", products_path, class: "navbar-wagon-item navbar-wagon-link", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% unanswered_questions.each do |product| %>
              <li>
                <%= link_to product.product_type, product_path(product), class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
            <% end %>

          </ul>
        </div>
      <% end %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.user_photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to '<i class="fa fa-user"></i> Profile'.html_safe, edit_user_registration_path %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to "Cadastre-se", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <% if user_signed_in? %>

      <!-- Links when logged in -->
      <%= link_to "Add Product", new_product_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "My Products", products_path, class: "navbar-wagon-item navbar-wagon-link" %>

      <% if question_count != 0 %>
        <div class="dropdown">
          <%= link_to "Questions (#{question_count})", products_path, class: "navbar-wagon-item navbar-wagon-link", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <% unanswered_questions.each do |product| %>
              <li>
                <%= link_to product.product_type, product_path(product), class: "navbar-wagon-item navbar-wagon-link" %>
              </li>
            <% end %>

          </ul>
        </div>
        <% else %>
          <%= link_to "Questions (#{question_count})", products_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% end %>
      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= cl_image_tag current_user.user_photo, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
      <% else %>
        <!-- Login link (when logged out) -->
        <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>



      </ul>
    </div>
  </div>
</div>